### ISSUE TITLE
1Blocker hides all comments

### ISSUE THREAD

**Issue by brettohland** [brettohland/fuckingformatstyles#1]
Looks like 1Blocker's rule for comments is a bit too specific:

``` CSS
.comment:not(.token):not(code) {
    display: none;
}
```
